name: build and test on Linux v2

on:
  workflow_dispatch:
  push:
    branches-ignore: [ main ]  
    paths:
    - '**.cs'
    - '**.csproj'
    tags-ignore:
    - 'v*.*.*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_VERSION: '8.0.204' # The .NET SDK version to use

permissions:
  contents: read

jobs:
  quick-workflow:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal