name: release

on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_VERSION: '8.0.204' # The .NET SDK version to use
  ARTIFACT_NAME : 'NumerologicalTool'
  PROJECT_NAME : 'NumerologicalLifePath.Application'

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install tools and restore
      run: dotnet restore

    - name: Build & Publish
      shell: powershell
      run: |
        $version =  ("${{ github.ref_name }}").TrimStart("v")
        dotnet build --configuration Release --no-restore -p:Version=$version
        dotnet publish ${{ env.PROJECT_NAME }} -c Release -r win-x64 --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true --self-contained true -p:UseAppHost=true -o publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}
        path: publish
